name: sovarpc
description: "SovaRPC"
publish_to: 'none'

version: 1.1.5

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  archive: ^3.4.10
  flutter_gen: ^5.3.1
  bloc: ^8.1.4
  drift: ^2.15.0
  path: ^1.8.3
  get_it: ^7.6.7
  http: ^1.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  noso_dart: 1.2.5
  noso_rest_api:
    git: https://github.com/nosocoin/noso_rest_api.git
  args: ^2.5.0
  settings_yaml: ^8.0.1
  logging: ^1.2.0
  logging_appenders: ^1.3.0
  ansicolor: ^2.0.2


dev_dependencies:
  drift_dev: ^2.15.0
  build_runner: ^2.4.6
